### ISSUE TITLE
Wire up ProxyAccount.managerCapabilityFilter into Capability retrieval

### ISSUE THREAD

**Issue by sisyphusSmiling** [Flowtyio/restricted-child-account#58]
As I understand it, `ProxyAccount.managerCapabilityFilter` is supposed to act as an additional filter on Capability retrieval; however, it's only ever set in the current contract.

To fulfill it's intended function, it should be checked in any method that retrieves a Capability. Those are:

- `getCapability()`
- `getPrivateCapFromProxy()`
- `getPublicCapFromProxy()`
- `getPublicCapability()`

**Comment by austinkline** [comment]
I actually ended up putting these in post conditions:
https://github.com/Flowtyio/restricted-child-account/blob/main/contracts/HybridCustody.cdc#L160

Do we think that isn't sufficient/isn't working as intended?

**Comment by austinkline** [comment]
Do public capabilities need to be covered, though? I'd assume no because if they're public, it doesn't matter what access we restrict, anyone can get to it anyway

**Comment by sisyphusSmiling** [comment]
Oh clever, sorry for the miss. True, it would be useless to try to restrict access to something public. I'll go ahead and close the issue
